version: '3.4'

services:
  chat.web:
    image: ${DOCKER_REGISTRY-}chatweb
    build:
      context: .
      dockerfile: Chat.Web/Dockerfile
    depends_on:
      - mssql-server
  
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "mssql"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=hVrurt3TfQL8GtHc9yssCpSq
      - MSSQL_PID=Express
    ports:
      - 1433:1433